name: gha:zad2

# Szablon workflow: Miejsca oznaczone "#" naley uzupełnić 

on:
  workflow_dispatch:
#  push:
#    branches: [ main ]

jobs:
  build:
    # Definicja systemu do instalacji na wźle roboczym 
    runs-on: ubuntu-latest
    
    steps:

      #Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Instalacja środowiska Docker + Buildx
      - name: Buildx set-up
        uses: docker/setup-buildx-action@v2

      # Instalacja QEMU
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2

      # Logowanie do Dockerhub-a
      # - name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{secrets.DOCKERHUB_USERNAME}}
      #     password: ${{secrets.DOCKERHUB_TOKEN}}

      #Logowanie do GHCR
      - name: GHCR Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.TOKEN_GHCR}}

      # Budowa obrazu dla dwóch architektur sprzętowych 
      # oraz przesłanie do własnego repo na Dockerhub
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/x86_64,linux/arm64
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{github.repository_owner}}/zad2:x86
            ghcr.io/${{github.repository_owner}}/zad2:arm64

